### ISSUE TITLE
How should we deal with "asset" references in recipes?

### ISSUE THREAD

**Issue by scymtym** [RDTK/organization#5]
## Problem

Some recipes use "asset" references in their `catalog` sections. There are two kinds of such references:

1. References to images. Example:

   ```yaml
   catalog:
     title: Nightly Builds of CogIMon Core Components
     version: nightly
     image:
     - catalog://cosima.png
     - catalog://kuka-lwr-sim.png
   ```

   The catalog export turns these into image links such as `https://toolkit.cit-ec.uni-bielefeld.de/sites/toolkit.cit-ec.uni-bielefeld.de/files/cosima.png`

2. References to descriptions. Example:

   ```yaml
   catalog:
     title: Robotics Service Bus
     version: nightly
     description: opensource://rsb-generic.md
   ```

   There are two issues:

   * The `opensource` schema doesn't make a lot of sense now

   * Having this special treatment for a certain magic syntax within the description field is no longer necessary since the more general include syntax should be usable to achieve the same result.

## Solution

1. Not sure. Maybe store the images alongside the recipes in the recipe repository?

2. The YAML include syntax seems like a good replacement.
